In [1]:
import os
import sqlite3
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# 1. قراءة الـ Master Dataset مباشرة من قاعدة البيانات
base_dir = r"D:\Courses\MachineLearning\Depi\Final Project\data"
db_path = os.path.join(base_dir, "urbanmind_ai.db")

conn = sqlite3.connect(db_path)
df = pd.read_sql_query("SELECT * FROM master_dataset", conn)
conn.close()

# 2. عرض أول 5 صفوف والمعلومات الأساسية
print(f"📊 Dataset Shape: {df.shape}")
display(df.head())

📊 Dataset Shape: (43, 21)

,zone_x,district_ar,district_en,males,females,total_population,families_count,avg_family_size,green_parks_sqm,dump_sites,...,recycling_plants,transfer_stations,zone_y,cleaning_societies_equipment,cleaning_societies_workers,companies_equipment,companies_workers,total_cleaning_workers,total_cleaning_equipment,workers_per_10k_capita
0,المنطقة الشرقية,مصر الجديدة,Heliopolis,73104,74240,147344,36836,4.0,175703.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,المنطقة الشرقية,النزهة,El Nozha,125931,128114,254045,63511,4.0,304800.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,المنطقة الشرقية,شرق مدينة نصر,East Nasr City,336356,360859,697215,174304,4.0,466045.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,المنطقة الشرقية,غرب مدينة نصر,West Nasr City,37567,41695,79262,19816,4.0,30685.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,المنطقة الشرقية,المطرية,El Matareya,322330,339443,661773,165443,4.0,6300.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [4]:
import urllib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sqlalchemy import create_engine

# 1. الاتصال بـ SQL Server وقراءة جدول master_dataset
server = r"REWANSHEHAB\SQLEXPRESS"
database = "UrbanMindDB"

db_conn_str = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(db_conn_str)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# 2. استعلام البيانات مباشرة
df = pd.read_sql("SELECT * FROM master_dataset", con=engine)

# 3. عرض الأبعاد وأول الصفوف
print(f"📊 Dataset Loaded from SQL Server! Shape: {df.shape}")
display(df.head())

📊 Dataset Loaded from SQL Server! Shape: (43, 21)

,zone_x,district_ar,district_en,males,females,total_population,families_count,avg_family_size,green_parks_sqm,dump_sites,...,recycling_plants,transfer_stations,zone_y,cleaning_societies_equipment,cleaning_societies_workers,companies_equipment,companies_workers,total_cleaning_workers,total_cleaning_equipment,workers_per_10k_capita
0,المنطقة الشرقية,مصر الجديدة,Heliopolis,73104,74240,147344,36836,4.0,175703.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,المنطقة الشرقية,النزهة,El Nozha,125931,128114,254045,63511,4.0,304800.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,المنطقة الشرقية,شرق مدينة نصر,East Nasr City,336356,360859,697215,174304,4.0,466045.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,المنطقة الشرقية,غرب مدينة نصر,West Nasr City,37567,41695,79262,19816,4.0,30685.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,المنطقة الشرقية,المطرية,El Matareya,322330,339443,661773,165443,4.0,6300.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0